entity_type_groups:
  node:
    article:
      basic: basic
      advanced: advanced
    component_page:
      basic: basic
      advanced: advanced
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_abstract: null
  metatag_maxlength_description: null
  metatag_maxlength_title: null
tag_scroll_max_height: ''
